apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: devops-quick-start-guide
  name: devops-quick-start-guide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-quick-start-guide
  template:
    metadata:
      labels:
        app: devops-quick-start-guide
    spec:
      containers:
        - name: devops-quick-start-guide
          image: dpills/devops-quick-start-guide:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 1Gi
