apiVersion: v1
kind: Service
metadata:
  labels:
    app: devops-quick-start-guide
  name: devops-quick-start-guide-svc
spec:
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: devops-quick-start-guide
